sebs-scholarship/sebs-scholarship

index.html
CHANGED - Facebook icon opens in new page
CHANGED - Shifted page header to the left
FIXED - Issue where header looked weird on mobile devices
=> Shifted header left and fixed mobile compatibility issue

assets/css/style.css, index.html
CHANGED - Bottom margin for parent bullet points to .5 rem
=> Small change to sublist spacing

assets/css/style.css, assets/js/main.js, index.html, robots.txt, sitemap.xml
ADDED - Countdown to display time until application opens (or until application closes), depending on current time
ADDED - Scroller animation to help users navigate the webpage
ADDED - Privacy policy
ADDED - robots.txt and sitemap.xml files to improve webcrawler experience
CHANGED - minor wording in About Us section
=> Added countdown, scroller, webcrawler files, and privacy policy

assets/js/main.js, index.html
CHANGED - Modified condition when to display navbar after hrefs are clicked
=> Changed navigation bar behavior

index.html
CHANGED - Email address now reflects a more professional email
CHANGED - Style/ordering of page footer
=> Changed email address and style of footer

index.html, sitemap.xml
CHANGED - Sitemap and Index to match Google chosen URL
=> Small SEO Optimization

index.html, privacy_policy.html, sitemap.xml
ADDED - Privacy policy
CHANGED - Privacy policy link on homepage
=> Added privacy policy

privacy_policy.html
FIXED - Canonical on privacy policy page
=> Fixed canonical

assets/images/site.webmanifest
FIXED - Incorrectly configured webmanifest
=> Fixed appearance on Android Chrome

.github/workflows/main.yml
ADDED - Github action for test site
=> Add test site configuration

privacy_policy.html
CHANGED - Privacy policy to use correct name
=> Corrected small typo in Privacy Policy

assets/css/style.css, index.html
CHANGED - Small improvements for website accessibility, such as use with screen readers
CHANGED - Reformatted CSS
=> Improve website accessibility

index.html
CHANGED - Apply links to point to a form that complies with SSF internal privacy protocols
=> Changed apply links to point to secure form

index.html
FIXED - URL in social meta code
=> Fixed social code

index.html
ADDED - Non-discriminatory Statement paragraph to the footer of homepage
=> Added Non-discriminatory Statement to homepae

index.html
ADDED - gtag.js code to head of homepage
=> Added analytics code to homepage

index.html
CHANGED - Apply buttons link to new security officer account
=> Updated links for new security officer account

apply/index.html
ADDED - Page to redirect traffic from a "/apply" link to the application requirements section.
=> Added redirect page

volunteer/index.html
ADDED - Redirect for "/volunteer" links
=> Added easy volunteering link

index.html
CHANGED - Preconnect to fonts.googleapis.com for faster loading
=> Optimized font loading

index.html
CHANGED - Wording of application requirements
=> Changed application requirements

assets/css/style.css, privacy_policy.html
CHANGED - Small correction to privacy policy
CHANGED - Phone number now correct color
=> Updated privacy policy

apply/index.html, donate/index.html, privacy_policy.html, robots.txt, tax_documents.html, volunteer/index.html
ADDED -  Descriptions and`og` meta properties to apply/ donate/ and volunteer/
ADDED - Icons to tax_documents.html and privacy_policy.html
CHANGED - Titles of apply/ donate/ and /volunteer
CHANGED - Disallow apply/ donate/ and /volunteer
FIXED - Description of tax_documents.html
=> Added more sharing information to easily shareable links

.circleci/config.yml, index.html
CHANGED - CircleCI config now deploys to production site
CHANGED - Less downtime during deployments to test and production sites
=> Migrate site to new host

email/contact.php, email/subscriptions.php, index.html, missing.html
ADDED - Newsletter button
CHANGED - Better validation in PHP forms
CHANGED - Contact form now enables/disables the button while sending to prevent spam
FIXED - 404 Page now loads correctly in all locations
=> Added Newsletter button

robots.txt
FIXED - robots.txt crawl error from blocked email folder
=> Fixed robots.txt error

.circleci/config.yml
ADDED - Syntax check for PHP files
=> Add syntax check for PHP

selection_process.html
FIXED - Link on selection process page linking to donation instead of contact
=> Fixed incorrect link

privacy_policy.html
FIXED - Accidentally used h5 in Privacy Policy header rather than h2
=> Fixed small typo in privacy policy code

assets/css/style.css, email/confirm.html, email/invalid.html, email/not-subscribed.html, email/subscribe.html, email/subscribed.html, email/success.html, email/unsubscribe.html, email/unsubscribed.html, forbidden.html, index.html, missing.html, privacy_policy.html, selection_process.html, tax_documents.html
ADDED - Cursor now changes to pointer when hovering over non-link buttons
ADDED - SSF Blog link to navbar
CHANGED - Wording of items in navbar
REMOVED - Requirements section of navbar
=> Added cursor stylings and SSF Blog

email/confirm.html, email/invalid.html, email/not-subscribed.html, email/subscribe.html, email/subscribed.html, email/success.html, email/unsubscribe.html, email/unsubscribed.html, forbidden.html, index.html, missing.html, privacy_policy.html, selection_process.html, tax_documents.html
FIXED - Issue that makes navbar appear poorly at some resolutions by changing navbar items to only use a single word
=> Fixed issue where navbar looked bad with double-word items

feedback/index.html, index.html
ADDED - Feedback form button after contact section
ADDED - Feedback form easy redirect
CHANGED - Header button now says "Learn More" and links to lower in the page instead of the closed application
=> Added feedback form and changed header button

index.html
CHANGED - Small wording change to feedback section
=> Changed wording

index.html
FIXED - Navbar opening issue when Learn More button is pressed
=> Fixed learn more issue causing navbar to open

email/contact.php, index.html
CHANGED - Updated volunteering links
CHANGED - Contact form updated to work with Freshdesk's API rather than as an email client
=> GSuite Migration Update

.github/workflows/push.yml
CHANGED - Super-linter now running v3.2.0 rather than latest v3
=> Dropped super linter version
